g29_force_feedback:
  ros__parameters:
    device_name: "/dev/input/by-id/usb-Logitech_G29_Driving_Force_Racing_Wheel-event-joystick"
    loop_rate: 0.1
    max_torque: 1.5
    min_torque: 0.2
    brake_torque: 0.05
    brake_position: 0.1
    auto_centering_max_torque: 0.1
    auto_centering_max_position: 1.0
    eps: 0.0
    auto_centering: true